namespace: master-k8s
images:
  api:
    repository: ghcr.io/kickoffqi/master-k8s-api
    tag: sha-d9a702a
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/kickoffqi/master-k8s-frontend
    tag: sha-798ffcc
    pullPolicy: IfNotPresent
replicaCount:
  api: 1
  frontend: 2
ingress:
  enabled: true
  className: nginx
  host: dev.master.local
api:
  corsAllowOrigins: "*"
frontend:
  publicApiBaseUrl: "/api"
rollouts:
  enabled: true
  # Canary strategy example: 20% -> 50% -> 100%
  canarySteps:
    - setWeight: 20
    - pause: { duration: 30s }
    - setWeight: 50
    - pause: { duration: 30s }
    - setWeight: 100
