namespace: master-k8s
images:
  api:
    repository: ghcr.io/kickoffqi/master-k8s-api
    tag: sha-b5deee7
    pullPolicy: IfNotPresent
  frontend:
    repository: ghcr.io/kickoffqi/master-k8s-frontend
    tag: sha-b5deee7
    pullPolicy: IfNotPresent
replicaCount:
  api: 2
  frontend: 1
ingress:
  enabled: true
  className: nginx
  host: master.local
api:
  corsAllowOrigins: "*"
frontend:
  publicApiBaseUrl: "/api"
