apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - servicemonitor-master-k8s-api-dev.yaml
  - servicemonitor-master-k8s-api-prod.yaml
  - grafana-dashboard-master-k8s-api.yaml
