apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: master-k8s
resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress-api.yaml
  - ingress-frontend.yaml
