apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - children/addon-monitoring-app-dashboards.yaml
  - children/addon-monitoring-app-metrics.yaml
  - children/addon-monitoring-rules.yaml
  - children/addon-monitoring.yaml
  - children/app-helm-dev.yaml
  - children/addon-argo-rollouts.yaml
  - children/addon-argocd-image-updater.yaml
  - children/imageupdater-master-k8s-helm-dev.yaml
