apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ops-readonly
  namespace: {{ .Values.namespace | quote }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "services", "endpoints", "events", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-readonly
  namespace: {{ .Values.namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: ops-readonly
    namespace: {{ .Values.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ops-readonly
