apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-api
  namespace: {{ .Values.namespace | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: events-frontend
  namespace: {{ .Values.namespace | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ops-readonly
  namespace: {{ .Values.namespace | quote }}
