{{- if not .Values.rollouts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-api
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: events-api
  template:
    metadata:
      labels:
        app: events-api
    spec:
      serviceAccountName: events-api
      automountServiceAccountToken: false
      containers:
        - name: api
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.api.tag }}"
          imagePullPolicy: {{ .Values.images.api.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
          env:
            - name: CORS_ALLOW_ORIGINS
              value: {{ .Values.api.corsAllowOrigins | quote }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
{{- end }}
