{{- if not .Values.rollouts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-frontend
  namespace: {{ .Values.namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: events-frontend
  template:
    metadata:
      labels:
        app: events-frontend
    spec:
      serviceAccountName: events-frontend
      automountServiceAccountToken: false
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: {{ .Values.images.frontend.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: {{ .Values.frontend.publicApiBaseUrl | quote }}
          
            - name: API_BASE_URL
              value: "http://events-api:8000"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
{{- end }}
