apiVersion: v1
kind: Service
metadata:
  name: events-frontend
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: events-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000