apiVersion: v1
kind: Service
metadata:
  name: events-api
  labels:
    app: events-api
  namespace: {{ .Values.namespace | quote }}
spec:
  selector:
    app: events-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000