apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/example/master-k8s-api
    newName: ghcr.io/kickoffqi/master-k8s-api
    newTag: latest
  - name: ghcr.io/example/master-k8s-frontend
    newName: ghcr.io/kickoffqi/master-k8s-frontend
    newTag: latest
